version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
#    networks:
#      - motivoo-net

  blue-api:
    container_name: blue-api
    image: yejunpark1/motivoo-api-server
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - redis
#    networks:
#      - motivoo-net

  green-api:
    container_name: green-api
    image: yejunpark1/motivoo-api-server
    expose:
      - 8080
    ports:
      - "8082:8080"
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - redis
#    networks:
#      - motivoo-net

#networks:
#  motivoo-net:
#    driver: bridge