name: Motivoo API Server CI

on:  # 트리거
  push:
    branches: [ "develop" ]
    paths:
      - motivoo-api/**
      - motivoo-domain/**
      - motivoo-common/**
      - motivoo-external/**
  pull_request:
    branches: [ "develop" ]
    paths:
      - motivoo-api/**
      - motivoo-domain/**
      - motivoo-common/**
      - motivoo-external/**

permissions:
  contents: read

jobs:
  build:  # job#1
    runs-on: ubuntu-22.04
    env:
      working-directory: ./  # 프로젝트 디렉토리

    steps:  # 작업 단위
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: Java 실행 환경 - JDK 17 세팅
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: application.yml (API 모듈) 파일 생성
        run: |
          # yml을 생성할 디렉터리로 작업 디렉터리 이동
          cd ./motivoo-api/src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./application-deploy.yml

        working-directory: ${{ env.working-directory }}

      - name: application.yml (Domain 모듈) 파일 생성
        run: |
          cd ./motivoo-domain/src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./application-deploy.yml

        working-directory: ${{ env.working-directory }}


      - name: Gradle Properties 파일 생성
        run: |
          echo "${{ secrets.GRADLE_PROPERTIES }}" > ./local.properties
        working-directory: ${{ env.working-directory }}

      - name: 빌드
        run: |
          chmod +x gradlew
          ./gradlew motivoo-api:bootJar
        working-directory: ${{ env.working-directory }}
        shell: bash

