name: CI

on:  # 트리거
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:  # job#1
    runs-on: ubuntu-22.04
    env:
      working-directory: ./  # 프로젝트 디렉토리

    steps:  # 작업 단위
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: Java 실행 환경 - JDK 17 세팅
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: application.yml 파일 생성
        run: |
          # yml을 생성할 디렉터리로 작업 디렉터리 이동
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./application-deploy.yml
        working-directory: ${{ env.working-directory }}


      - name: Firebase JSON 파일 생성
        run: |
          cd ./src/main/resources

          mkdir ./firebase
          cd ./firebase
          echo $(ls -al)

          aws s3 cp --region ap-northeast-2 s3://${{ secrets.S3_BUCKET_PATH }}/motivoo-firebase-adminsdk.json .
          echo $(ls -al; pwd)

        shell: bash

      - name: Gradle Properties 파일 생성
        run: |
          mkdir local.properties
          echo "${{ secrets.GRADLE_PROPERTIES }}" > ./local.properties
        working-directory: ${{ env.working-directory }}

      - name: 빌드
        run: |
          chmod +x gradlew
          ./gradlew build
        working-directory: ${{ env.working-directory }}
        shell: bash

